package com.worklog.draft.dto;

import com.worklog.draft.Draft;
import com.worklog.draft.DraftStatus;
import java.time.LocalDate;
import java.time.OffsetDateTime;

/**
 * GET /drafts 의 항목 (PRD 7). 홈 화면의 사용자 카드가 배지와 버튼을 고르는 데만 쓰므로
 * 본문(contentMd)은 싣지 않는다. 담당자 1의 목업 `frontend/src/mocks/drafts.json` 과 같은 모양.
 */
public record DraftSummaryResponse(
        Long id,
        Long userId,
        LocalDate workDate,
        Integer version,
        DraftStatus status,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt,
        OffsetDateTime confirmedAt,
        /** 스케줄러가 만든 초안인지 (V4). 화면이 "자동 생성됨" 을 표시한다. */
        boolean autoGenerated,
        /** 사용자가 저장한 적이 있는지 (V6). 있으면 스케줄러가 덮지 않는다. */
        boolean userEdited,
        /** DAILY · WEEKLY · REPO (V15). 화면이 탭을 가른다. */
        com.worklog.draft.DraftKind kind,
        /** WEEKLY·REPO 의 기간. DAILY 는 workDate 하루다. */
        LocalDate periodStart,
        LocalDate periodEnd,
        Long repoId,
        String repoFullName) {

    public static DraftSummaryResponse from(Draft d) {
        return new DraftSummaryResponse(
                d.getId(),
                d.getUser().getId(),
                d.getWorkDate(),
                d.getVersion(),
                d.getStatus(),
                d.getCreatedAt(),
                d.getUpdatedAt(),
                d.getConfirmedAt(),
                d.isAutoGenerated(),
                d.isUserEdited(),
                d.getKind(),
                d.getPeriodStart(),
                d.getPeriodEnd(),
                d.getRepo() == null ? null : d.getRepo().getId(),
                d.getRepo() == null ? null : d.getRepo().getFullName());
    }
}
