package com.worklog.draft;

import com.worklog.activity.Activity;
import com.worklog.activity.ActivityRepository;
import com.worklog.auth.User;
import com.worklog.auth.UserRepository;
import com.worklog.config.ApiException;
import com.worklog.config.KstDates;
import com.worklog.vscode.VscodeSession;
import com.worklog.vscode.VscodeSessionRepository;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * 하루치 활동을 묶어 업무 일지 초안을 만든다 (PRD F3a — 담당자 2 소유).
 *
 * <p>조회·수정·확정 API 는 담당자 1의 {@code DraftController} 다. 이 클래스는 생성만 한다.
 */
@Service
public class DraftGenerator {

    private static final Logger log = LoggerFactory.getLogger(DraftGenerator.class);

    private final ActivityRepository activityRepository;
    private final VscodeSessionRepository sessionRepository;
    private final DraftRepository draftRepository;
    private final UserRepository userRepository;
    private final WorklogWriter worklogWriter;

    public DraftGenerator(
            ActivityRepository activityRepository,
            VscodeSessionRepository sessionRepository,
            DraftRepository draftRepository,
            UserRepository userRepository,
            WorklogWriter worklogWriter) {
        this.activityRepository = activityRepository;
        this.sessionRepository = sessionRepository;
        this.draftRepository = draftRepository;
        this.userRepository = userRepository;
        this.worklogWriter = worklogWriter;
    }

    /**
     * 초안 1건 생성.
     *
     * @return 활동도 세션도 없으면 {@link Optional#empty()} — 컨트롤러가 204 로 답한다 (PRD F3)
     */
    /** 사용자가 버튼을 눌러 만드는 경로. */
    @Transactional
    public Optional<Draft> generate(Long userId, LocalDate workDate) {
        return generate(userId, workDate, false);
    }

    /**
     * @param automatic 18:00 스케줄러가 부른 것이면 true. 화면이 "자동 생성됨" 을 표시해,
     *     내가 만들지 않은 초안이 왜 있는지 알 수 있게 한다 (V4).
     */
    @Transactional
    public Optional<Draft> generate(Long userId, LocalDate workDate, boolean automatic) {
        User user = userRepository
                .findById(userId)
                .orElseThrow(() -> ApiException.notFound("USER_NOT_FOUND", "사용자를 찾을 수 없습니다."));

        List<Activity> activities = activityRepository.findForUserBetween(
                userId, KstDates.startOf(workDate), KstDates.endOf(workDate));
        // 행이 있다는 것만으로는 재료가 아니다. 확장이 10분마다 보내므로, 열어만 두고 아무것도
        // 하지 않은 날에도 빈 세션이 쌓인다. 그것으로 일지를 만들면 아무것도 하지 않은 날에
        // AI 가 일지를 지어낸다 (9/11 확인).
        List<VscodeSession> sessions = sessionRepository.findByUserIdAndWorkDate(userId, workDate).stream()
                .filter(VscodeSession::hasContent)
                .toList();

        if (activities.isEmpty() && sessions.isEmpty()) {
            log.info("{} 의 {} 활동이 없어 초안을 만들지 않는다.", user.getLogin(), workDate);
            return Optional.empty();
        }

        Draft draft = new Draft();
        draft.setUser(user);
        draft.setWorkDate(workDate);
        // 덮어쓰지 않고 버전을 올린다. 확정본은 그대로 남는다 (PRD F3).
        draft.setVersion(draftRepository.findMaxVersion(userId, workDate) + 1);
        draft.setStatus(DraftStatus.DRAFT);
        draft.setAutoGenerated(automatic);
        // 활동 행을 늘어놓지 않고 하루치를 통으로 읽어 쓴다 (BACKLOG F-1).
        // 실패하면 WorklogWriter 가 템플릿으로 돌아간다.
        draft.setContentMd(
                worklogWriter.write(userId, workDate, displayName(user), activities, sessions));
        draft.setSourceActivityIds(activities.stream().map(Activity::getId).toArray(Long[]::new));
        draft.setSourceSessionIds(sessions.stream().map(VscodeSession::getId).toArray(Long[]::new));

        Draft saved = draftRepository.save(draft);
        log.info(
                "{} 의 {} 초안 v{} 생성 — 활동 {}건, 세션 {}건",
                user.getLogin(),
                workDate,
                saved.getVersion(),
                activities.size(),
                sessions.size());
        // 초안을 만들었다고 알리지는 않는다 (9/11 결정). 사원이 AI 생성을 누를 때마다
        // 관리자 채널에 글이 쌓였는데, 아직 사람이 손대지 않은 초안이라 알릴 것이 못 된다.
        // 알림은 사원이 [Mattermost 전송] 을 눌렀을 때 한 번만 나간다 (NotifyService.notifyDraftSummarized).
        // 그래서 여기서는 NotifyService 를 아예 받지 않는다 — 받아 두면 쓰지도 않는 의존이 남고,
        // 채팅으로 일지를 만들 수 있게 되면서 고리가 된다
        // (MattermostBot → WorkLogAnswerService → DraftGenerator → NotifyService → MattermostBot).
        return Optional.of(saved);
    }

    /**
     * 그날 활동이 있는 전 사용자에 대해 생성한다 (18:00 스케줄러).
     *
     * <p>이미 확정한 초안이 있으면 건너뛴다 — 사용자가 확정한 내용을 자동 생성이 덮지 않는다.
     *
     * @return 만든 초안 수
     */
    @Transactional
    public int generateForAll(LocalDate workDate) {
        List<Long> userIds = activityRepository.findUserIdsWithActivityBetween(
                KstDates.startOf(workDate), KstDates.endOf(workDate));
        int created = 0;
        for (Long userId : userIds) {
            if (draftRepository.existsByUserIdAndWorkDateAndStatus(
                    userId, workDate, DraftStatus.CONFIRMED)) {
                log.info("사용자 {} 의 {} 일지는 이미 완료돼 있어 건너뛴다.", userId, workDate);
                continue;
            }
            // 저장만 하고 완료하지 않았어도 사람이 쓴 것이다. 자동 생성이 뒤로 밀면 안 된다 (V6).
            if (draftRepository.existsByUserIdAndWorkDateAndUserEditedTrue(userId, workDate)) {
                log.info("사용자 {} 의 {} 일지는 직접 저장한 내용이 있어 건너뛴다.", userId, workDate);
                continue;
            }
            if (generate(userId, workDate, true).isPresent()) {
                created++;
            }
        }
        return created;
    }

    private static String displayName(User user) {
        return user.getName() != null && !user.getName().isBlank() ? user.getName() : user.getLogin();
    }
}
