package com.worklog.draft;

import com.worklog.auth.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * 하루치 업무 일지 초안 (PRD F3).
 *
 * <p><b>공동 소유 엔티티.</b> 1일차 오전 공통 작업으로 확정했으므로, 필드 추가·변경은 두 담당자 합의 후에만 한다
 * (PRD 2. 컨플릭트 방지). 생성 로직은 담당자 2의 {@code DraftGenerator}, 조회·수정·확정 API 는 담당자 1이 맡는다.
 *
 * <p>같은 (user, workDate) 에 재생성하면 덮어쓰지 않고 version 을 올려 새 행을 만든다.
 */
@Entity
// 버전 유니크는 (user, kind, work_date, repo, version) 부분 인덱스로 옮겼다 (V15).
// repo_id 가 NULL 인 행끼리도 막아야 해서 제약이 아니라 coalesce 를 쓴 인덱스다.
@Table(name = "drafts")
@Getter
@Setter
@NoArgsConstructor
public class Draft {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** KST 기준 업무 일자. */
    @Column(name = "work_date", nullable = false)
    private LocalDate workDate;

    /** 하루치·주간·저장소별 (V15). 기존 행은 전부 DAILY. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private DraftKind kind = DraftKind.DAILY;

    /** WEEKLY·REPO 의 기간. DAILY 는 null 이고 workDate 하루가 곧 기간이다. */
    @Column(name = "period_start")
    private LocalDate periodStart;

    @Column(name = "period_end")
    private LocalDate periodEnd;

    /** REPO 일지가 다루는 저장소. 리포를 지워도 일지는 남는다 (ON DELETE SET NULL). */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "repo_id")
    private com.worklog.github.Repo repo;

    /** 기간의 시작 — DAILY 면 그날. 화면·알림이 "언제 것인지" 를 한 가지로 읽게 한다. */
    public LocalDate from() {
        return periodStart != null ? periodStart : workDate;
    }

    public LocalDate to() {
        return periodEnd != null ? periodEnd : workDate;
    }

    @Column(nullable = false)
    private Integer version = 1;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private DraftStatus status = DraftStatus.DRAFT;

    /** 18:00 스케줄러가 만들었으면 true (V4). 사용자가 버튼을 눌러 만들었으면 false. */
    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated = false;

    /**
     * 사용자가 저장한 적이 있으면 true (V6).
     *
     * <p>18:00 스케줄러는 이 값이 true 인 날을 건너뛴다. 사람이 쓴 내용이 자동 생성으로
     * 뒤로 밀리면 안 된다 (9/10 결정).
     */
    @Column(name = "user_edited", nullable = false)
    private boolean userEdited = false;

    @Column(name = "content_md", nullable = false, columnDefinition = "text")
    private String contentMd;

    /** 이 초안의 근거가 된 activity id 목록. 초안 편집 화면 우측에 함께 보여준다. */
    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "source_activity_ids", nullable = false, columnDefinition = "bigint[]")
    private Long[] sourceActivityIds = new Long[0];

    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "source_session_ids", nullable = false, columnDefinition = "bigint[]")
    private Long[] sourceSessionIds = new Long[0];

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    @Column(name = "confirmed_at")
    private OffsetDateTime confirmedAt;

    @PrePersist
    void onCreate() {
        OffsetDateTime now = OffsetDateTime.now();
        if (createdAt == null) {
            createdAt = now;
        }
        updatedAt = now;
    }

    @PreUpdate
    void onUpdate() {
        updatedAt = OffsetDateTime.now();
    }
}
