/**
 * PRD 7. API 명세의 응답 타입. 목업 JSON(`src/mocks/`)과 실서버 응답이 같은 모양이어야 하므로
 * 필드명을 임의로 바꾸지 않는다. 목록은 배열, `/activities` 만 페이지 래퍼를 쓴다
 * (docs/HANDOFF_day1_integration.md 2.).
 */

export type ActivityType = 'COMMIT' | 'PR_OPENED' | 'PR_MERGED'
export type SummaryStatus = 'PENDING' | 'DONE' | 'FAILED'
export type DraftStatus = 'DRAFT' | 'CONFIRMED'
export type SyncStatus = 'OK' | 'SYNCING' | 'FAILED'

export interface Me {
  id: number
  /** GitHub 로그인. 연동하지 않았으면 빈 문자열이다 (사원번호 로그인으로 바뀐 뒤). */
  login: string
  name: string | null
  avatarUrl: string | null
  /** 사원번호 네 자리. 회원 조회 API 의 empSeq 를 채운 값 (9/10 회의). */
  loginId?: string
  role?: 'MEMBER' | 'ADMIN'
  mustChangePassword?: boolean
}

export interface UserRef extends Me {}

/**
 * `POST /auth/login` — 사원번호와 비밀번호로 로그인한다 (9/10 회의).
 * 관리자 콘솔도 같은 경로를 쓰고 `role` 로 갈린다.
 */
export interface LoginRequest {
  /** 사원번호 네 자리 (예: 0042). 관리자는 admin */
  loginId: string
  password: string
}

export interface LoginResponse {
  token: string
  /** true 면 비밀번호를 바꾸기 전까지 다른 화면으로 갈 수 없다. */
  mustChangePassword: boolean
  role: 'MEMBER' | 'ADMIN'
}

/** `GET /me/github` — 내 계정에 붙은 GitHub. 붙이지 않았으면 linked=false. */
export interface GithubLink {
  linked: boolean
  login: string | null
  avatarUrl: string | null
  linkedAt: string | null
}

export interface RepoRef {
  id: number
  fullName: string
}

export interface Repo {
  id: number
  fullName: string
  defaultBranch: string | null
  lastSyncedAt: string | null
  registeredBy: { id: number; login: string }
  /** 그날 이 리포의 커밋 수 — 리포 관리 Table "오늘 활동 수" */
  todayActivityCount: number
  syncStatus: SyncStatus
}

export interface Activity {
  id: number
  type: ActivityType
  repo: RepoRef
  /** 가입하지 않은 GitHub 계정의 활동은 null 이고 externalLogin 만 채워진다 (PRD F1-5). */
  user: UserRef | null
  externalLogin: string | null
  /** COMMIT 은 sha, PR_OPENED/PR_MERGED 는 PR 번호 */
  externalId: string
  sha: string | null
  title: string
  url: string
  branch: string | null
  filesChanged: number | null
  additions: number | null
  deletions: number | null
  summary: string | null
  summaryStatus: SummaryStatus
  occurredAt: string
}

export interface Page<T> {
  items: T[]
  page: number
  size: number
  total: number
}

/** `GET /activities/{id}` — 목록 항목에 커밋 메시지와 diff 본문을 더한다. */
export interface ActivityDetail extends Activity {
  message: string | null
  /** 수집기가 아직 채우지 않아 항상 null 이다 (TODO_0910 §4 F-2). */
  rawDiff: string | null
}

export interface UncommittedFile {
  path: string
  additions: number
  deletions: number
  diff?: string
}

export interface TodoItem {
  path: string
  line: number
  text: string
}

export interface EditTimelineEntry {
  path: string
  firstSavedAt: string
  lastSavedAt: string
  saveCount: number
}

/** 그 폴더에서 오간 AI 대화 한 세션. 사용자가 친 말만 담는다. */
export interface AiSessionSummary {
  id: string
  firstAt: string
  lastAt: string
  promptCount: number
  prompts: string[]
}

export interface VscodeSession {
  id: number
  userId: number
  repo: RepoRef | null
  remoteUrl: string
  branch: string
  workDate: string
  uncommittedFiles: UncommittedFile[]
  todos: TodoItem[]
  planNote: string | null
  editTimeline: EditTimelineEntry[]
  /** 커밋에도 미커밋 변경에도 남지 않는 작업의 단서. */
  aiSessions: AiSessionSummary[]
  summary: string | null
  lastCommitAt: string | null
  reportedAt: string
}

/** `GET /drafts` — 목록에는 본문을 싣지 않는다. */
export interface DraftSummary {
  id: number
  userId: number
  workDate: string
  version: number
  status: DraftStatus
  createdAt: string
  updatedAt: string
  confirmedAt: string | null
  /** 18:00 스케줄러가 만든 초안인지. 사용자가 버튼을 눌러 만들었으면 false. */
  autoGenerated: boolean
  /** 사용자가 저장한 적이 있는지. 있으면 스케줄러가 덮지 않는다. */
  userEdited: boolean
}

/** `GET /drafts/{id}` — 근거를 객체로 펼친 상세. */
export interface Draft extends DraftSummary {
  contentMd: string
  sourceActivities: Activity[]
  sourceSessions: VscodeSession[]
}

/**
 * `POST /drafts/generate` 응답. 상세(Draft)와 **모양이 다르다** — 근거가 객체가 아니라 id 배열이고
 * 타임스탬프가 없다. 상세 캐시에 그대로 넣으면 화면이 sourceActivities 를 못 찾아 터진다.
 */
export interface GeneratedDraft {
  id: number
  userId: number
  workDate: string
  version: number
  status: DraftStatus
  contentMd: string
  sourceActivityIds: number[]
  sourceSessionIds: number[]
}

export interface DailyStats {
  date: string
  commits: number
  prs: number
  merges: number
  sessions: number
  /** "어제 대비 +3" */
  commitsDelta: number
  /** "⚠ 6시간 이상 1건" */
  staleSessions: number
  /**
   * 사용자에 연결되지 않은 활동 수. 총계 = byUser 합계 + unmapped 가 항상 성립한다.
   * 가입하지 않은 외부 기여자의 커밋이 여기 잡힌다.
   */
  unmapped: { commits: number; prs: number; merges: number }
  byUser: { userId: number; commits: number; prs: number; merges: number; sessions: number }[]
}

export interface PeopleSeriesPoint {
  date: string
  commits: number
  prs: number
  merges: number
  draft: { id: number; status: DraftStatus } | null
}

export interface PeopleStats {
  from: string
  to: string
  granularity: 'day' | 'week'
  items: {
    user: UserRef
    totals: { commits: number; prs: number; merges: number }
    series: PeopleSeriesPoint[]
  }[]
}

export interface ApiKey {
  id: number
  label: string
  createdAt: string
  lastUsedAt: string | null
}

/**
 * 발급 직후 한 번만 평문 키가 온다. 목록 항목(ApiKey)과 달리 `lastUsedAt` 이 없다 —
 * 방금 만든 키라 사용 이력이 있을 수 없다. 상속하면 타입이 실제 응답을 속인다.
 */
export interface IssuedApiKey {
  id: number
  label: string
  key: string
  createdAt: string
}

export interface NotifySettings {
  mattermostWebhookUrl: string | null
  remindUncommitted: boolean
}

export interface LlmSettings {
  provider: 'gemma4' | 'qwen3'
  presets: { id: 'gemma4' | 'qwen3'; model: string; connected: boolean }[]
}

/** 오류 형식은 전부 이 모양이다 (HANDOFF 3.). */
export interface ApiErrorBody {
  code: string
  message: string
}
