import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { CalendarDays, ChevronRight, ExternalLink } from 'lucide-react'
import AutoBadge from '@/components/common/AutoBadge'
import { DraftStatusBadge } from '@/components/common/StatusBadge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { Textarea } from '@/components/ui/textarea'
import {
  useDailyStats, useDraft, useDraftRange, useDrafts, useGenerateDraft, useMe, useSaveDraft, useSessions,
} from '@/api/hooks'
import { useSelectedDate } from '@/hooks/useSelectedDate'
import { formatDateLabel, formatTime } from '@/lib/date'
import { cn } from '@/lib/utils'
import type { DraftSummary } from '@/types/api'

const RANGES = [
  { days: 14, label: '2주' },
  { days: 30, label: '한 달' },
  { days: 90, label: '3개월' },
]

function daysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString().slice(0, 10)
}

/**
 * 업무 일지 작성 — 오늘 것은 맨 위에서 만들고, 지난 것은 아래 목록에서 펼쳐 고친다.
 *
 * <p>일지는 "생성" 을 눌렀을 때만 만들어진다. 서버가 그날의 깃허브 내역과 VS 내역을
 * 함께 모아 쓴다 (PRD F3).
 */
export default function DraftsPage() {
  const navigate = useNavigate()
  const { date } = useSelectedDate()
  const { data: me } = useMe()

  const [days, setDays] = useState(14)
  const list = useDraftRange({ from: daysAgo(days), to: date, userId: me?.id }, Boolean(me))

  const today = useDrafts({ date, userId: me?.id })
  const stats = useDailyStats(date)
  const sessions = useSessions({ date, userId: me?.id })
  const generate = useGenerateDraft()

  const todayDraft = today.data?.[0]
  const myStat = stats.data?.byUser.find((u) => u.userId === me?.id)
  const mySessions = (sessions.data ?? []).filter((s) => s.userId === me?.id)
  const material = (myStat?.commits ?? 0) + (myStat?.prs ?? 0) + mySessions.length

  // 오늘 것은 맨 위 카드가 이미 보여 준다. 목록에서는 뺀다.
  const past = (list.data ?? []).filter((d) => d.workDate !== date)

  async function onGenerate() {
    if (!me) return
    const created = await generate.mutateAsync({ date, userId: me.id })
    if (created && 'id' in created) navigate(`/drafts/${created.id}`)
  }

  return (
    <div className="space-y-4">
      <Card className="flex items-center justify-between gap-4 rounded-lg p-4 shadow-none">
        <div className="min-w-0">
          <p className="flex items-center gap-2 text-sm font-semibold">
            {formatDateLabel(date)}
            {todayDraft?.autoGenerated && <AutoBadge />}
            {todayDraft?.status === 'CONFIRMED' && <DraftStatusBadge status="CONFIRMED" />}
          </p>
          <p className="mt-0.5 text-[12px] text-muted-foreground">
            {todayDraft
              ? `버전 ${todayDraft.version} · 수정 ${formatTime(todayDraft.updatedAt)}`
              : material > 0
                ? `근거 ${material}건 — 깃허브 내역과 VS 내역을 모아 씁니다`
                : '이 날짜에는 일지를 만들 활동이 없습니다'}
          </p>
        </div>
        <div className="flex shrink-0 items-center gap-3">
          {todayDraft ? (
            <>
              <Button variant="outline" size="sm" className="h-[34px]"
                onClick={() => navigate(`/drafts/${todayDraft.id}`)}>
                열기
              </Button>
              <Button variant="outline" size="sm" className="h-[34px]"
                disabled={generate.isPending} onClick={() => void onGenerate()}>
                재생성
              </Button>
            </>
          ) : (
            <Button size="sm" className="h-[34px]"
              disabled={generate.isPending || material === 0} onClick={() => void onGenerate()}>
              업무 일지 생성
            </Button>
          )}
        </div>
      </Card>

      <div className="flex items-center justify-between">
        <h2 className="flex items-center gap-1.5 text-sm font-semibold">
          <CalendarDays className="size-4" />
          지난 업무 일지
        </h2>
        <div className="flex h-[30px] overflow-hidden rounded-md border">
          {RANGES.map((r, i) => (
            <button
              key={r.days}
              type="button"
              onClick={() => setDays(r.days)}
              className={cn(
                'px-3 text-[12px] transition-colors',
                i > 0 && 'border-l',
                days === r.days ? 'bg-primary/10 font-medium text-primary' : 'text-muted-foreground hover:bg-muted',
              )}
            >
              {r.label}
            </button>
          ))}
        </div>
      </div>

      <Card className="overflow-hidden rounded-lg shadow-none">
        {list.isLoading ? (
          <div className="space-y-2 p-4"><Skeleton className="h-9" /><Skeleton className="h-9" /></div>
        ) : past.length === 0 ? (
          <p className="px-6 py-12 text-center text-[13px] text-muted-foreground">
            이 기간에 쓴 지난 업무 일지가 없습니다.
          </p>
        ) : (
          past.map((d) => <PastRow key={d.id} draft={d} onOpen={() => navigate(`/drafts/${d.id}`)} />)
        )}
      </Card>
    </div>
  )
}

/**
 * 지난 일지 한 줄 — 누르면 그 자리에서 펼쳐 고친다.
 *
 * <p>본문은 목록 응답에 없다. 펼칠 때만 상세를 받아 온다.
 * 근거 패널·재생성·Mattermost 전송이 필요하면 편집 화면을 연다.
 */
function PastRow({ draft, onOpen }: { draft: DraftSummary; onOpen: () => void }) {
  const [open, setOpen] = useState(false)
  const detail = useDraft(open ? draft.id : undefined)
  const save = useSaveDraft()

  const [text, setText] = useState<string | null>(null)
  const content = text ?? detail.data?.contentMd ?? ''
  const dirty = text !== null && text !== detail.data?.contentMd

  async function onSave() {
    await save.mutateAsync({ id: draft.id, contentMd: content })
    setText(null)
  }

  return (
    <div className="border-b last:border-b-0">
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className="flex w-full items-center gap-3 px-4 py-3 text-left transition-colors hover:bg-muted/60"
      >
        <ChevronRight className={cn('size-3.5 shrink-0 text-muted-foreground transition-transform', open && 'rotate-90')} />
        <span className="w-[120px] shrink-0 text-[13px] font-medium tabular-nums">
          {formatDateLabel(draft.workDate)}
        </span>
        {draft.status === 'CONFIRMED' && <DraftStatusBadge status="CONFIRMED" />}
        {draft.autoGenerated && <AutoBadge />}
        <span className="text-[12px] text-muted-foreground">버전 {draft.version}</span>
        <span className="min-w-0 flex-1" />
        <span className="shrink-0 text-[12px] text-muted-foreground">
          수정 {formatTime(draft.updatedAt)}
        </span>
      </button>

      {open && (
        <div className="space-y-2 border-t bg-muted/30 px-4 py-3">
          {detail.isLoading ? (
            <Skeleton className="h-40" />
          ) : (
            <>
              <Textarea
                value={content}
                onChange={(e) => setText(e.target.value)}
                readOnly={draft.status === 'CONFIRMED'}
                className="min-h-[220px] bg-background font-mono text-[12px] leading-relaxed"
              />
              <div className="flex items-center gap-2">
                <Button size="sm" className="h-8"
                  disabled={!dirty || save.isPending || draft.status === 'CONFIRMED'}
                  onClick={() => void onSave()}>
                  {save.isPending ? '저장 중…' : '저장'}
                </Button>
                <Button variant="outline" size="sm" className="h-8 gap-1.5" onClick={onOpen}>
                  <ExternalLink className="size-3.5" />
                  편집 화면에서 열기
                </Button>
                <span className="text-[12px] text-muted-foreground">
                  근거 확인·재생성·Mattermost 전송은 편집 화면에서 합니다
                </span>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  )
}
